[NEW] Commands
mohamedmagdy/odoo-pycharm-templates pull request #9
Opened 2017-01-17 15:54 UTC by mstuttgart

* Added snippets to *create* and *write* methods .
* Added snippet to *group* tag in xml.
* Import Odoo snippet in alphabetical order

2017-03-05 23:15 UTC, mstuttgart commented
@mohamedmagdy

2017-03-05 23:33 UTC, mohamedmagdy commented on Odoo.xml
> +  <template name="odoo_field_integer" value="new_field = fields.Integer(string='', required=False, )" description="Add new field of type Integer" toReformat="false" toShortenFQNames="true">
Great work, @mstuttgart . 
Can you help me to understand why you replaced the double qoutes to be the single quote !!

Thank you :)

2017-03-06 01:39 UTC, mstuttgart commented on Odoo.xml
> +  <template name="odoo_field_integer" value="new_field = fields.Integer(string='', required=False, )" description="Add new field of type Integer" toReformat="false" toShortenFQNames="true">
It is only as visual improvement. A guess the python code more clean when use `single quotes`. 

I can turn back it if you dont like.

2017-04-18 21:16 UTC, mohamedmagdy approved these changes

2017-04-18 21:19 UTC, mohamedmagdy requested changes
@mstuttgart , You are doing a great job and I really appreciate it.
Well, in most cases Odoo is using the double quotes and in few times it uses single quotes. So, I think it will be easier for the odoo developers to see it in double quotes, What do you think?

2017-04-18 21:30 UTC, mstuttgart commented
@mohamedmagdy no problem! I update the commits history and remove this commit. 

I added snippets to button, button-box, field and field 'state' in XML.

2017-04-18 21:35 UTC, mohamedmagdy approved these changes
Thank you, @mstuttgart for being active :)
I am accepting this pull request with pleasure :+1:

2017-04-18 21:37 UTC, mohamedmagdy commented
@mstuttgart , as you can see there is a conflict. It will be nice of you to solve it whenever you have time.

Thank you :)

2017-04-18 21:44 UTC, mstuttgart commented
@mohamedmagdy fixed! Thanks! :100:

2017-04-18 21:45 UTC, merged

2017-04-18 21:46 UTC, mohamedmagdy commented
@mstuttgart , no it is me who should thank you :)